# docker-compose.yml
version: '3.9'
services:
  game:
    image: your-marvel-headless
    volumes: ["./shared:/shared"]
    entrypoint: ["start_game_headless.sh"]
    deploy: { replicas: 8 }
  learner:
    build: .
    volumes: ["./shared:/shared"]
    command: python train.py
